<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Create' => '',
  'Create Group' => '',
  'Edit Group "{name}"' => '',
  'Import' => '',
  'Import Groups' => '',
  'Manage Groups' => '',
  'Name' => '',
  'Save' => '',
  'ext. Name' => '',
  'group already imported' => '',
  'group already imported; different groupnames found' => '',
  'please define a display name' => ''
);
