<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'assignedVMs' => 'MVs asignadas',
  'createSubnet' => 'crear subred',
  'createUser' => 'crear usuario',
  'createVmProfile' => 'crear perfil MV',
  'createVmTemplate' => 'editar plantilla MV',
  'editVmProfile' => 'editar perfil MV',
  'editVmTemplate' => 'editar plantilla MV',
  'manageNodes' => 'gestionar nodos',
  'manageSubnets' => 'gestionar subredes',
  'manageUser' => 'gestionar usuario',
  'manageVMProfiles' => 'gestionar perfiles MV',
  'manageVMTemplates' => 'gestionar plantillas MV',
  'manageVMs' => 'gestionar MVs',
  'updateUser' => 'actualizar usuario',
  'updateVM' => 'actualizar MV',
  'uploadIso' => 'actualizar Iso',
  'viewNode' => 'ver nodo',
  'viewVM' => 'ver MV',
);
