<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Assigned VMs' => 'MVs asignadas',
  'Create' => 'Crear',
  'Download Spice Client' => 'Descargar cliente Spice',
  'Dynamic Virtual Machines' => 'MVs dinámicas',
  'Dynamic Virtual Machines Tooltip' => 'Lista de Máquinas Virtuales dinámicas',
  'Links' => 'Vínculos',
  'Network' => 'Red',
  'Node' => 'Nodo',
  'Nodes' => 'Nodos',
  'Nodes Tooltip' => 'Nodos definidos',
  'Node Create Tooltip' => 'Creación de nodos',
  'Node View Tooltip' => 'Vistas de nodo',
  'Spice Client Tooltip' => 'Clientes Spice',
  'Persistent Virtual Machines' => 'MVs persistentes',
  'Persistent Virtual Machines Tooltip' => 'Máquinas Virtuales persistentes',
  'Storage Pool' => 'Grupo de almac.',
  'Storage Pools' => 'Grupo de almac.',
  'Storage Pools Tooltip' => 'Agrupaciones de almacenamiento',
  'Storage Pool Create Tooltip' => 'Creación de agrupaciones de almacenamiento',
  'Storage Pool View Tooltip' => 'Vistas',
  'Subnet Create Tooltip' => 'Creación de subred',
  'Subnet Tooltip' => 'Subred',
  'Subnets' => 'Subredes',
  'Update' => 'Editar',
  'Upload Iso File' => 'Actualizar archivo ISO',
  'User' => 'Usuario',
  'User Create Tooltip' => 'Creación de nuevo usuario',
  'User Tooltip' => 'Usuario',
  'User Update Tooltip' => 'Actualización de usuario',
  'View' => 'Vista',
  'Virtual Machine' => 'Máquina Virtual',
  'Virtual Machine Profile Update Tooltip' => 'Actualización de perfil de Máquina Virtual',
  'Virtual Machine Profile UploadIso Tooltip' => 'Subida Iso de perfil de Máquina Virtual',
  'Virtual Machine Profiles' => 'Perfiles',
  'Virtual Machine Template Update Tooltip' => 'Plantilla de actualización de Máquina Virtual',
  'Virtual Machine Templates' => 'Plantillas MV',
  'Virtual Machine Update Tooltip' => 'Actualización de Máquina Virtual',
  'Virtual Machine Profile Create Tooltip' => 'Crear nuevo perfil MV',
  'Virtual Machine Profiles Tooltip' => 'Lista de MV definidas',
  'Virtual Machine Template Create Tooltip' => 'Crear nueva plantilla MV',
  'Virtual Machine Templates Tooltip' => 'Lista de plantillas MV definidas',
  'VmList' => 'Lista MV',
  'VmList Tooltip' => 'Lista de MVs disponibles',
  'VM Pool' => 'Agrupación MV',
  'VM Pools' => 'Agrupaciones MV',
  'VM Pools Tooltip' => 'Agrupaciones MV',
  'VM Pool Create Tooltip' => 'Creación de agrupaciones MV',
  'VM Pool View Tooltip' => 'Vistas de agrupaciones MV',
);
