<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Name already in use!' => 'Este nombre ya está siendo utilizado',
  'Not a valid IP Address!' => 'Dirección IP incorrecta',
  'wizard.outputvar \'{var}\' missing' => 'no se encuentra wizard.outputvar \'{var}\'',
 '"{nodename}" is already integrated!' => '"{nodename}" ya está integrado!',
  'Manage Nodes' => 'Gestionar nodos',
  'View Node {name}' => 'Ver nodos \'{name}\'',
  'Node' => 'nodo',
  'Type' => 'tipo',
  'wizard.type' => 'Tipo de nodo',
  'wizard.ip' => 'IP',
  'wizard.user' => 'Usuario',
  'wizard.password' => 'Contraseña',
  'wizard.passwordcheck' => 'Introducir contraseña otra vez',

  'wizard.test1.title' => 'Red de control de integración de nodos',
  'wizard.test1.0' => 'El script se ejecutó correctamente.',
  'wizard.test1.1' => 'El script terminó en estado indefinido.',
  'wizard.test1.2' => 'No se aprobó el nombre del módulo.',

  'wizard.prov1.title' => 'Sistema de archivos de integración de aprovisionamiento de nodos',
  'wizard.prov1.0' => 'El script se ejecutó correctamente.',
  'wizard.prov1.1' => 'El script terminó en estado indefinido.',
);
