<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Incorrect username or password.' => 'Nombre de usuario o contraseña incorrectos',
  'Incorrect username.' => 'Este usuario no existe.',
  'Incorrect password.' => 'Contraseña incorrecta.',
  'Password' => 'Contraseña ',
  'Realm' => 'Dominio',
  'Remember me next time' => 'Recordarme la próxima vez',
  'User not assigned to realm.' => 'Usuario no asignado a división',
  'Username' => 'Nombre de usuario',
);
