<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Broadcast Address' => 'Dirección de difusión',
  'Create' => 'Crear',
  'Create subnet' => 'Crear subred',
  'Default Gateway' => 'Puerta de enlace predeterminada',
  'Domain Name' => 'Nombre de dominio (con " ")',
  'Domain Server(s)' => 'Servidor (es) de dominio',
  'IP Start Address' => 'Dirección IP inicial',
  'Manage Subnets' => 'Gestionar subredes',
  'NTP Server(s)' => 'Servidor (es) NTP',
  'Not a valid IP Address!' => 'Dirección IP incorrecta',
  'Save' => 'Guardar',
  'Net Mask' => 'Máscara de subred',
  'Type' => 'Tipo',
  'Overlaps with subnet {subnet}' => 'Se solapa con subred {subnet}',
  'Overlaps with range {range}' => 'Se solapa con rango {range}',
  'Not within subnet {subnet}' => 'Fuera de subred {subnet}',
  'title' => 'título',
);
