<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Admin' => 'Admin',
  'Assign VMs to user' => 'Asignar MVs a usuario',
  'Assigned VMs' => 'MVs asignadas',
  'Assignment saved!' => 'Asignación guardada',
  'Create' => 'Crear',
  'Create User' => 'Crear usuario',
  'Edit User "{name}"' => 'Editar usuario "{name}"',
  'Female' => 'Hembra',
  'Mail already in use!' => 'Este correo ya está siendo utilizado',
  'Male' => 'Macho',
  'Manage User' => 'Gestionar usuario',
  //'PHP function mhash and mhash_keygen_s2k for encryption type "SSHA"' => 'Función PHP mhash y mhash_keygen_s2k para tipo de cifrado "SSHA"',
  //'PHP function mhash needed to encode password for encryption type "SSHA"' => Para asignar una contraseña al tipo de cifrado "SSHA" se requiere la función PHP mhash',
  'Save' => 'Guardar',
  //'Unknown encryption type "{type}" for LDAP user authentication!' => '',
  //'Username already in use!' => 'Este nombre de usuario ya existe',
  'VM User' => 'Usuario MV',
  'VMs' => 'MVs',
  //'{attribute} is invalid. Please use only<br/>"0-9+()" characters and blank.' => '{attribute} incorrect. Utilice solamente caracteres <br/>"0-9+()" y espacios',
  'gender' => 'Género',
  'givenname' => 'Apellido',
  'mail' => 'Correo electrónico',
  'mobile' => 'Móvil',
  'password' => 'Contraseña',
  'passwordcheck' => 'Introducir contraseña otra vez',
  'surname' => 'Nombre',
  'telephone' => 'Teléfono',
  'username' => 'Nombre de usuario',
  'userrole' => 'Rol de usuario',
);
