<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Create dynamic VM' => 'Crear MV dinámica',
  'Create persistent VM' => 'Crear MV persistente',
  'Edit VM "{name}" ({type})' => 'Editar MV "{name}" ({type})',
  'Golden Image activated!' => 'Golden Image activada',
  'Golden Image already activated!' => 'La Golden Image ya está activada',
  'Migration finished' => 'Migración terminada',
  'No range found for VMPool!' => 'No se encuentra rango para VMPool',
  'Parameter dn not found!' => 'No se encuentra parámetro',
  'VM Details "{name}"' => 'Detalles MV "{name}"',
  'VM with dn=\'{dn}\' not found!' => 'No se encuentra MV con dn=\'{dn}\'',
  'dynamic VM Pools' => 'VM Pools dinámicas',
  'persistent VM Pools' => ' VM Pools persistente',
  'Assign users to VM' => 'Asignar usuarios a MV',
  'Assigned users' => 'Usuarios asignados',
  'Assignment saved!' => 'Asignación guardada',
  'Description' => 'Descripción',
  'IP Address already in use!' => 'Esta dirección IP ya está siendo utilizada',
  'IP Address not in range!' => 'Esta dirección IP no se encuentra dentro del rango',
  'IP Address required!' => 'Se require dirección IP',
  'Manage {type} VMs' => 'Gestionar {type} MVs',
  'Migrate' => 'Migrar',
  'Migrate VM "{name}"' => 'Migrar MV "{name}"',
  'Name already in use!' => 'Este nombre ya está siendo utilizado',
  'Nodes' => 'Nodos',
  'Please select a range!' => 'Seleccione un rango',
  'Save' => 'Guardar',
  'Users' => 'Usuarios',
  'ip' => 'Dirección IP',
  'name' => 'Nombre',
  'sstClockOffset' => 'Compensación de reloj',
  'sstMemory' => 'Memoria',
  'sstVCPU' => 'CPU',
  'sstVolumeCapacity' => 'capacidad de volumen',
  'staticIP' => 'cambiar dirección IP',
  'title' => 'título',
);
