<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Assign users to VM Pool' => 'Asignar usuarios a MV Pool',
  'Assigned users' => 'Usuarios asignados',
  'Assignment saved!' => 'Asignación guardada',
  'Create' => 'Crear',
  'Create VM Pool' => 'Crear MV Pool',
  'Edit Storage Pool "{name}"' => 'Editar agrupación de almacenamiento "{name}"',
  'Edit VM Pool "{name}"' => 'Editar MV Pool "{name}"',
  'Manage VM Pools' => 'Gestionar MV Pools',
  'Save' => 'Guardar',
  'Users' => 'Usuarios',
  'brokerMax' => 'Broker Máx.',
  'brokerMin' => 'Broker Mín.',
  'brokerPreStart' => 'Pre-arranque Broker',
  'changes the selection of StoragePools and Ranges!' => 'cambia la selección de rangos y agrupaciones de almacenamiento',
  'displayName' => 'Nombre',
  'nodes' => 'Nodos',
  'range' => 'Rango',
  'storagepool' => 'Agrupación de almacenamiento',
  'description' => 'Descripción',
);
