<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Action' => 'Acción',
  'Architecture' => 'Arquitectura',
  'BaseProfile' => 'PerfilBase',
  'Check ISO Copy' => 'Compruebe copia ISO',
  'Copy of ISO file still running!' => 'Copia de archivo ISO aún en funcionamento',
  'Create' => 'Crear',
  'Description' => 'Descripción',
  'Edit VMProfile "{name}"' => 'Editar perfil MV "{name}"',
  'Extension uploadprogress not installed!' => 'La extensión progresodesubida no está instalada',
  'File Name' => 'Nombre de archivo',
  'Finished!' => 'Terminado',
  'Iso File' => 'Archivo Iso',
  'Language' => 'Idioma',
  'Manage VMProfiles' => 'Gestionar perfilesMV',
  'Name' => 'Nombre',
  'No.' => 'Nº',
  'Save' => 'Guardar',
  'Still copying!' => 'Copia en curso',
  'Upload Iso File' => 'Upload ISO File',
  'Upload finished ({total})' => 'Subida completa ({total})',
  'Create VMProfile' => 'Crear perfil MV',
  'Name already in use!' => 'Este nombre ya está siendo utilizado',
  'No file for upload!' => 'Ningún archivo seleccionado para subir',
  'Upload error ({errno}).' => 'Error de subida ({errno}).',
  'Uploading... ({uploaded} of {total})' => 'Subiendo... ({uploaded} de {total})',
  'sstClockOffset' => 'Compensación de reloj',
  'sstMemory' => 'Memoria',
  'sstVCPU' => 'CPU',
  'sstVolumeCapacity' => 'Capacidad de volumen',
  'step1' => 'Paso I',
  'step1text' => 'Seleccionar un perfil',
  'step2' => 'Paso II',
  'step2text' => 'Sobrescribir los valores predeterminados si es necesario',
  'title' => 'Título',
  'Please use only a-z, A-Z, 0-9, the space and the _ character.' => 'Utilizar solamente caracteres a-z, A-Z, 0-9, espacio y guión bajo (_).',
  'Upload finished' => 'Upload finished!',
  'Upload finished title' => 'Finished',
  'Unload message' => 'Note: If you leave this page the upload is stopped!\\nDo you want to stop the upload?',
  'Alternative upload method' => '',
  'Alternative upload method link' => 'http://www.foss-cloud.org/en/wiki/Upload_ISO-Files',
);
