<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Description' => 'Descripción',
  'No Range in Subnet ({subnet}) found! <a href="{anker}">Please create one.</a>' => 'No se encontró rango en subred ({subnet}) <a href="{anker}">Por favor, crear subred',
  'No Subnet found! <a href="{anker}">Please create one.</a>' => 'No se encontró subred. <a href="{anker}">Por favor, crear subred.',
  'No free IP in Range {range} (Subnet {subnet}) found!' => 'No se encontró IP libre en rango {range} (subred {subnet})',
  'No free IP in Ranges of VmPool {pool} found!' => 'No se encontró IP libre en los rangos de la agrupación de almacenamiento MV {pool}',
  'No range found for VMPool!' => 'No se encuentra rango para MVPool',
  'No storagepool found for selected vmpool!' => 'No se encontró agrupación de almacenamiento para la mvpool seleccionada',
  'Start VM' => 'Arrancar MV',
  'Unable to create Volume file!' => 'Imposible crear archivo de volumen',
  'Check Volume Copy' => 'Comprobar copia de directorio',
  'Copy of VM Template volume to VM volume still running!' => 'Copia de plantilla MV a volumen MV en curso',
  'Create' => 'Crear',
  'Create VmTemplate' => 'Crear Plantilla MV',
  'Edit VMTemplate "{name}"' => 'Editar Plantilla MV "{name}"',
  'Finished!' => 'Terminado',
  'Manage VMTemplates' => 'Gestionar Plantillas MV',
  'Name already in use!' => 'Este nombre ya está siendo utilizado',
  'Node' => 'Nodo',
  'Profile' => 'Perfil',
  'Save' => 'Guardar',
  'Still copying!' => 'Copia en progreso',
  'ip' => 'Dirección IP',
  'sstClockOffset' => 'Compensación de reloj',
  'sstMemory' => 'Memoria',
  'sstVCPU' => 'CPU',
  'sstVolumeCapacity' => 'Capacidad de volumen',
  'staticIP' => 'Cambio de dirección IP',
  'step1' => 'Paso I',
  'step1text' => 'Seleccionar un perfil',
  'step2' => 'Paso II',
  'step2text' => 'Seleccionar un nodo y sobrescribir los valores predeterminados si es necesario',
  'title' => 'Título',
);
