<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'BACKEND_XML_UNCONSISTENCY' => 'Backend XML unconsistency',
  'BACKUP_ROOT_DIRECTORY_DOES_NOT_EXIST' => 'Backup root directory does not exist',
  'CANNOT_CONNECT_TO_BACKEND' => 'Can not connect to backend',
  'CANNOT_COPY_BACKEND_FILE_TO_BACKUP_LOCATION' => 'Can not copy backend file to backup location',
  'CANNOT_COPY_FILE_TO_BACKUP_LOCATION' => 'Can not copy file to backup location',
  'CANNOT_COPY_IMAGE_TO_BACKUP_LOCATION' => 'Can not copy image to backup location',
  'CANNOT_COPY_STATE_FILE_TO_RETAIN' => 'Can not copy state file to retain',
  'CANNOT_COPY_XML_TO_BACKUP_LOCATION' => 'Can not copy XML to backup location',
  'CANNOT_CREATE_DIRECTORY' => 'Can not create directory',
  'CANNOT_CREATE_EMPTY_DISK_IMAGE' => 'Can not create empty disk image',
  'CANNOT_CREATE_TARBALL' => 'Can not create tarball',
  'CANNOT_DEFINE_MACHINE' => 'Can not define machine',
  'CANNOT_FIND_CONFIGURATION_ENTRY' => 'Can not find configuration entry',
  'CANNOT_FIND_MACHINE' => 'Can not find machine',
  'CANNOT_LOCK_MACHINE' => 'Can not lock machine',
  'CANNOT_MERGE_DISK_IMAGES' => 'Can not merge disk images',
  'CANNOT_MOVE_DISK_IMAGE_TO_ORIGINAL_LOCATION' => 'Can not move disk image to original location',
  'CANNOT_READ_STATE_FILE' => 'Can not read state file',
  'CANNOT_READ_XML_FILE' => 'can not read XML file',
  'CANNOT_REMOVE_FILE' => 'Can not remove file',
  'CANNOT_REMOVE_OLD_DISK_IMAGE' => 'Can not remove old disk image',
  'CANNOT_RENAME_DISK_IMAGE' => 'Can not rename disk image',
  'CANNOT_RESTORE_MACHINE' => 'Can not restore machine',
  'CANNOT_SAVE_BACKEND_ENTRY' => 'Can not save backend entry',
  'CANNOT_SAVE_MACHINE_STATE' => 'Can not save machine state',
  'CANNOT_SAVE_XML' => 'Can not save XML',
  'CANNOT_SET_DIRECTORY_OWNERSHIP' => 'Can not set directory ownership',
  'CANNOT_SET_DIRECTORY_PERMISSION' => 'Can not set directory permission',
  'CANNOT_SET_DISK_IMAGE_OWNERSHIP' => 'Can not set disk image ownership',
  'CANNOT_SET_DISK_IMAGE_PERMISSION' => 'Can not set disk image permission',
  'CANNOT_START_MACHINE' => 'Can not start machine',
  'CANNOT_WORK_ON_UNDEFINED_OBJECT' => 'Can not work on undefined object',
  'CANNOT_WRITE_TO_BACKUP_LOCATION' => 'Can not write to backup location',
  'CONFIGURED_RAM_DISK_IS_NOT_VALID' => 'Configured ram disk is not valid',
  'CORRUPT_DISK_IMAGE_FOUND' => 'Corrupt disk image found',
  'MISSING_NECESSARY_FILES' => 'Missing necessary files',
  'MISSING_PARAMETER_IN_CONFIG_FILE' => 'Missing parameter in config file',
  'NOT_ALL_FILES_DELETED_FROM_RETAIN_LOCATION' => 'Not all files deleted from retain location',
  'NOT_ENOUGH_SPACE_ON_RAM_DISK' => 'Not enough space on ran disk',
  'RETAIN_ROOT_DIRECTORY_DOES_NOT_EXIST' => 'Retain root directory does not exist',
  'UNDEFINED_ERROR' => 'Undefined error',
  'UNKNOWN_BACKEND_TYPE' => 'Unknown backend type',
  'UNKNOWN_ERROR' => 'Unknown error',
  'UNSUPPORTED_CONFIGURATION_PARAMETER' => 'Unsupported configuration parameter',
  'UNSUPPORTED_FILE_TRANSFER_PROTOCOL' => 'Unsupported file transfer protocol',
  'WRONG_STATE_INFORMATION' => 'Wrong state information',
);