<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Backup' => '',
  'Global' => '',
  'Save' => '',
  'Schedule' => '',
  'allow Sound' => '',
  'allow USB' => '',
  'at' => '',
  'max. Spice port' => '',
  'min. Spice port' => '',
  'no schedule' => '',
  'no. of iterations' => '',
  'vm force start' => '',
  'every day' => '',
  'vm force start hint' => <<<EOS
Force start virtual machine in the case of not being able<br/>to restore the virtual machine state during the backup process.<br/>
<b>Attention:</b> If set to Yes, this could lead to file system<br/>inconsistencies in the virtual machine.
EOS
,
);
