<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Assigned VMs' => '',
  'Create' => '',
  'Download Spice Client' => '',
  'Dynamic Virtual Machines' => 'Dynamic VMs',
  'Dynamic Virtual Machines Tooltip' => 'List of dynamic virtual machines',
  'Links' => '',
  'Network' => '',
  'Node' => '',
  'Nodes' => '',
  'Nodes Tooltip' => 'List of defined nodes',
  'Node Create Tooltip' => '',
  'Node View Tooltip' => '',
  'Spice Client Tooltip' => '',	
  'Persistent Virtual Machines' => 'Persistent VMs',
  'Persistent Virtual Machines Tooltip' => 'List of persistent virtual machines',
  'Storage Pool' => '',
  'Storage Pools' => '',
  'Storage Pools Tooltip' => '',
  'Storage Pool Create Tooltip' => '',
  'Storage Pool View Tooltip' => '',
  'Subnet Create Tooltip' => 'Create a network subnet',
  'Subnet Tooltip' => '',
  'Subnets' => '',
  'Update' => 'Edit',
  'Upload Iso File' => 'Upload ISO File',
  'User' => '',
  'User Create Tooltip' => 'Create a new User',
  'User Tooltip' => '',
  'User Update Tooltip' => '',
  'View' => '',
  'Virtual Machine' => '',
  'Virtual Machine Profile Update Tooltip' => '',
  'Virtual Machine Profile UploadIso Tooltip' => '',
  'Virtual Machine Profiles' => 'Profiles',
  'Virtual Machine Template Update Tooltip' => '',
  'Virtual Machine Templates' => 'VM Templates',
  'Virtual Machine Update Tooltip' => '',
  'Virtual Machine Profile Create Tooltip' => 'Create a new VM Profile',
  'Virtual Machine Profiles Tooltip' => 'List of defined VM Profiles',
  'Virtual Machine Template Create Tooltip' => 'Create a new VM Template',
  'Virtual Machine Templates Tooltip' => 'List of defined VM Templates',
  'VmList' => 'VM list',
  'VmList Tooltip' => 'List of available VM\'s',
  'VM Pool' => '',
  'VM Pools' => '',
  'VM Pools Tooltip' => '',
  'VM Pool Create Tooltip' => '',
  'VM Pool View Tooltip' => '',
);
