<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Name already in use!' => '',
  'Not a valid IP Address!' => '',
  'wizard.outputvar \'{var}\' missing' => '',
 '"{nodename}" is already integrated!' => '"',
  'Manage Nodes' => '',
  'View Node' => '',
  'node' => 'Node',
  'type' => 'Type',
  'wizard.type' => 'Node type',
  'wizard.ip' => 'IP',
  'wizard.user' => 'User',
  'wizard.password' => 'Password',
  'wizard.passwordcheck' => 're-enter Password',

  'wizard.test1.title' => 'Node Integration Check Network',
  'wizard.test1.0' => 'The script was executed successfully.',
  'wizard.test1.1' => 'The script ended in an undefined state.',
  'wizard.test1.2' => 'No module name was passed.',

  'wizard.prov1.title' => 'Node Integration Provisioning Filesystem',
  'wizard.prov1.0' => 'The script was executed successfully.',
  'wizard.prov1.1' => 'The script ended in an undefined state.',
);
