<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Broadcast Address' => '',
  'Create' => '',
  'Create subnet' => '',
  'Default Gateway' => '',
  'Domain Name' => 'Domain Name (with " ")',
  'Domain Server(s)' => '',
  'IP Start Address' => '',
  'Manage Subnets' => '',
  'NTP Server(s)' => '',
  'Not a valid IP Address!' => '',
  'Save' => '',
  'Subnet Mask' => '',
  'Type' => '',
  'Overlaps with subnet {subnet}' => '',
  'Overlaps with range {range}' => '',
  'Not within subnet {subnet}' => '',
  'title' => '',
);
