<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Assign VMs to user' => '',
  'Assigned VMs' => '',
  'Assignment saved!' => '',
  'Create' => '',
  'Create User' => '',
  'Edit User "{name}"' => '',
  'Female' => '',
  'Groupname already in use!' => '',
  'Mail already in use!' => '',
  'Male' => '',
  'Manage User' => '',
  'PHP function mhash and mhash_keygen_s2k for encryption type "SSHA"' => '',
  'PHP function mhash needed to encode password for encryption type "SSHA"' => '',
  'Please use only<br/>"0-9+()" characters and blank.' => '',
  'Please use only<br/>a-z, 0-9 and the _ character.' => '',
  'Save' => '',
  'Unknown encryption type "{type}" for LDAP user authentication!' => '',
  'Username already in use!' => '',
  'VMs' => '',
  'gender' => 'Gender',
  'givenname' => 'Given name',
  'language' => 'Language',
  'mail' => 'Email',
  'mobile' => 'Mobile',
  'password' => 'Password',
  'passwordcheck' => 're-enter Password',
  'surname' => 'Surname',
  'telephone' => 'Telephone',
  'username' => 'Username',
  'userrole' => 'Userrole',
);
