<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Create dynamic VM' => '',
  'Create persistent VM' => 'Create Persistent VM',
  'Edit VM "{name}" ({type})' => '',
  'Golden Image activated!' => '',
  'Golden Image already activated!' => '',
  'Migration finished' => '',
  'No range found for VMPool!' => '',
  'Parameter dn not found!' => '',
  'VM Details "{name}"' => '',
  'VM with dn=\'{dn}\' not found!' => '',
  'dynamic VM Pools' => '',
  'persistent VM Pools' => 'Persistent VM Pools',
  'Assign users to VM' => '',
  'Assigned users' => '',
  'Assignment saved!' => '',
  'Description' => '',
  'IP Address already in use!' => '',
  'IP Address not in range!' => '',
  'IP Address required!' => '',
  'Manage {type} VMs' => '',
  'Migrate' => '',
  'Migrate VM "{name}"' => '',
  'Name already in use!' => '',
  'Nodes' => '',
  'Please select a range!' => '',
  'Save' => '',
  'Users' => '',
  'ip' => 'IP Address',
  'name' => 'Name',
  'sstClockOffset' => 'Clockoffset',
  'sstMemory' => 'Memory',
  'sstVCPU' => 'CPU',
  'sstVolumeCapacity' => 'Volume Capacity',
  'staticIP' => 'change IP address',
  'title' => 'Title',
  'Assigned groups' => '',
  'Backup with dn=\'{dn}\' not found!' => '',
  'Groups' => '',
  'Restore Vm started!' => 'Restore of the Vm started!<br />Please wait for possible questions that might arise during the restore.',
  'Waiting for data' => 'Wait for answer ...',
  'Should restore of Vm start?' => 'Vm can be restored!<br />do you want to start?',
);
