<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Assign groups to VM' => '',
  'Assign groups to VM Pool' => '',
  'Assign users to VM Pool' => '',
  'Assigned groups' => '',
  'Assigned users' => '',
  'Assignment saved!' => '',
  'Create' => '',
  'Create VM Pool' => '',
  'Edit Storage Pool "{name}"' => '',
  'Edit VM Pool "{name}"' => '',
  'Groups' => '',
  'Manage VM Pools' => '',
  'NO' => '',
  'Save' => '',
  'Users' => '',
  'YES' => '',
  'allowSound (gloabal: NO)' => 'Sound (global: NO)',
  'allowSound (gloabal: YES)' => 'Sound (global: YES)',
  'allowUsb (gloabal: NO)' => 'USB (global: NO)',
  'allowUsb (gloabal: YES)' => 'USB (global: YES)',
  'brokerMax' => 'Broker Max',
  'brokerMin' => 'Broker Min',
  'brokerPreStart' => 'Broker Prestart',
  'brokerPreStartInterval' => 'Broker Prestart Interval',
  'changes the selection of StoragePools and Ranges!' => '',
  'description' => 'Description',
  'displayName' => 'Name',
  'global backup' => 'Global Backup',
  'global cron' => 'Global Schedule',
  'interfaces' => 'Interfaces',
  'no active Golden-Image' => 'Please set one Golden-Image as active for the selected VM Pool',
  'nodes' => 'Nodes',
  'pool backup' => 'VM Pool Backup',
  'poolSound' => 'use Sound',
  'poolUsb' => 'use USB',
  'range' => 'Range',
  'sstNumberOfScreens' => 'Number of displays',
  'storagepool' => 'StoragePool',
);
