<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Assign groups to VM' => '',
  'Assign groups to VM Pool' => '',
  'Assigned groups' => '',
  'Groups' => '',
  'Assign users to VM Pool' => '',
  'Assigned users' => '',
  'Assignment saved!' => '',
  'Create' => '',
  'Create VM Pool' => '',
  'Edit Storage Pool "{name}"' => '',
  'Edit VM Pool "{name}"' => '',
  'Manage VM Pools' => '',
  'Save' => '',
  'Users' => '',
  'brokerMax' => 'Broker Max',
  'brokerMin' => 'Broker Min',
  'brokerPreStart' => 'Broker Prestart',
  'changes the selection of StoragePools and Ranges!' => '',
  'displayName' => 'Name',
  'nodes' => 'Nodes',
  'range' => 'Range',
  'storagepool' => 'StoragePool',
  'description' => 'Description',
);
