<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Action' => '',
  'Architecture' => '',
  'BaseProfile' => '',
  'Check ISO Copy' => '',
  'Copy of ISO file still running!' => '',
  'Create' => '',
  'Description' => '',
  'Edit VMProfile "{name}"' => '',
  'Extension uploadprogress not installed!' => '',
  'File Name' => '',
  'Finished!' => '',
  'Iso File' => '',
  'Language' => '',
  'Manage VMProfiles' => '',
  'Name' => '',
  'No.' => '',
  'Save' => '',
  'Still copying!' => '',
  'Upload Iso File' => 'Upload ISO File',
  'Upload finished ({total})' => '',
  'Create VMProfile' => 'Create VM Profile',
  'Name already in use!' => 'Name already in use!',
  'No file for upload!' => 'No file for upload!',
  'Upload error ({errno}).' => 'Upload error ({errno}).',
  'Uploading... ({uploaded} of {total})' => 'Uploading... ({uploaded} of {total})',
  'sstClockOffset' => 'Clock Offset',
  'sstMemory' => 'Memory',
  'sstVCPU' => 'CPU',
  'sstVolumeCapacity' => 'Volume Capacity',
  'step1' => 'Step I',
  'step1text' => 'Please select a profile first!',
  'step2' => 'Step II',
  'step2text' => 'Overwrite the default values if necessary!',
  'title' => 'Title',
  'Please use only a-z, A-Z, 0-9, the space and the _ character.' => '',
);
