<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Description' => 'Beschreibung',
  'No Range in Subnet ({subnet}) found! <a href="{anker}">Please create one.</a>' => '',
  'No Subnet found! <a href="{anker}">Please create one.</a>' => '',
  'No free IP in Range {range} (Subnet {subnet}) found!' => '',
  'No free IP in Ranges of VmPool {pool} found!' => '',
  'No range found for VMPool!' => '',
  'No storagepool found for selected vmpool!' => '',
  'Start VM' => '',
  'Unable to create Volume file!' => '',
  'Check Volume Copy' => '',
  'Copy of VM Template volume to VM volume still running!' => '',
  'Create' => '',
  'Cancel' => '',
  'Create VmTemplate' => '',
  'Edit VMTemplate "{name}"' => '',
  'Finished!' => '',
  'Manage VMTemplates' => '',
  'Name already in use!' => '',
  'Node' => '',
  'Ok' => '',
  'Profile' => '',
  'Save' => '',
  'Still copying!' => '',
  'ip' => 'IP Address',
  'sstClockOffset' => 'Clock Offset',
  'sstMemory' => 'Memory',
  'sstVCPU' => 'CPU',
  'sstVolumeCapacity' => 'Volume Capacity',
  'staticIP' => 'change IP address',
  'step1' => 'Step I',
  'step1text' => 'Please select a profile first!',
  'step2' => 'Step II',
  'step2text' => 'Please choose a node and overwrite the default values if necessary!',
  'title' => 'Title',
);
