<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Action "{actionName}" (line {lineno} following) has the following errors: {messages}' => '',
  'CANCEL' => 'ABBRECHEN',
  'Destination directory "{dirName}" not allowed to overwrite!' => 'Überschreiben des Verzeichnises "{dirName}" ist nicht erlaubt!',
  'Destination file "{destName}" not allowed to overwrite!' => 'Überschreiben der Datei "{destName}" ist nicht erlaubt!',
  'Directory "{dirName}" not found!' => 'Verzeichnis "{dirName}" nicht vorhanden!',
  'Do you really want to start this patch?' => 'Wollen Sie diesen Patch jetzt starten?',
  'Error in line {lineno}: Action "{actionName}"; {message}' => 'Fehler in Zeile {lineno}: Aktion "{actionName}"; {message}',
  'Error in line {lineno}: Action without "name" attribute found!' => 'Fehler in Zeile {lineno}: Aktion ohne "name" Attribut gefunden!',
  'Error in line {lineno}: Parameter without "name" attribute within the action "{actionName}" found!' => 'Fehler in Zeile {lineno}: Parameter ohne "name" Attribut innerhalb der Aktion "{actionName}" gefunden!',
  'Error in line {lineno}: Parameter with empty "name" attribute within the action "{actionName}" found!' => 'Fehler in Zeile {lineno}: Parameter mit leerem "name" Attribut innerhalb der Aktion "{actionName}" gefunden!',
  'Error: Parameter with name "{paramName}" within the action "{actionName}" not found!' => 'Fehler: Parameter "{paramName}" innerhalb der Aktion "{actionName}" nicht gefunden!',
  'Error in line {lineno}: Unknown action "{actionName}" found!' => 'Fehler in Zeile {lineno}: Unbekannte Aktion "{actionName}" gefunden!',
  'Error in line {lineno}: Parameter without "name" attribute within the mainClass found!' => 'Fehler in Zeile {lineno}: Parameter ohne "name" Attribut innerhalb der mainClass gefunden!',
  'Error in line {lineno}: Parameter with empty "name" attribute within the mainClass found!' => 'Fehler in Zeile {lineno}: Parameter mit leerem "name" Attribut innerhalb der mainClass gefunden!',
  'Error: Parameter with name "{paramName}" within the mainClass not found!' => 'Fehler: Parameter "{paramName}" innerhalb der mainClass nicht gefunden!',
  'Error in line {lineno}: Unknown finish type "{finishType}" found!' => 'Fehler in Zeile {lineno}: Unbekannter finish type "{finishType}" gefunden!',
  'finished: {message}!' => 'beendet: {message}!',
  'finished: {actionCount} of {actionCount} actions processed!' => 'beendet: {actionCount} von {actionCount} Aktionen verarbeitet!',
  'File "{fileName}" not found!' => 'Datei "{fileName}" nicht vorhanden!',
  'List of available patches' => 'Liste verfügbarer Patches',
  'Mandatory parameter "{paramName}" missing!' => 'Obligatorischer Paramter "{paramName}" fehlt!',
  'Mandatory XML tag "{xmlTag}" missing!' => 'Obligatorisches XML Tag "{xmlTag}" fehlt!',
  'OK' => 'JA',
  'Part progress' => 'Teil-Fortschritt',
  'Patch: {title}' => '',
  'Patch (version from {minVersion} to {maxVersion}) not allowed with this actual version ({actVersion})' => 'Patch (Version von {minVersion} bis {maxVersion}) ist nicht erlaubt mit dieser Version ({actVersion})',
  'The two parameters "{paramName1}" and "{paramName2}" must both have a &lt;set&gt; or not!' => '',
  'The two parameters "{paramName1}" and "{paramName2}" must both have the same number of &lt;item&gt; in their own &lt;set&gt;!' => '',
  'Total progress' => 'Gesamt-Fortschritt',
  'Unable to delete file "{fileName}"!' => 'Datei "{fileName} konnte nicht gelöscht werden!',
  'Unable to move patch to archive!' => 'Patch konnte nicht ins Archiv verschoben werden!',
  'Unable to delete patch!' => 'Patch konnte nicht geschlöscht werden!',
  'Unknown action "{actionName}"!' => 'Unbekannte Aktion "{actionName}"',
  'Unknown patch with name "{patchName}"!' => 'Unbekannter Patch "{patchName}"!',
  'start patch' => 'Start Patch',
);
