<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Can\'t connect to Ldap Server.' => 'Verbindung zum LDAP Server kann nicht hergestellt werden.',
  'Can\'t move uploaded file.' => 'Die hochgeladene Datei kann nicht verschoben werden.',
  'Can\'t open input stream.' => '',
  'Can\'t open output stream.' => '',
  'Can\'t open temporary directory.' => '',
  'locale' => 'de_DE',
);
