<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
	'UNDEFINED_ERROR' => 'Undefined error',
	'MISSING_PARAMETER_IN_CONFIG_FILE' => 'Missing parameter in config file',
	'CONFIGURED_RAM_DISK_IS_NOT_VALID' => 'Configured ram disk is not valid',
	'NOT_ENOUGH_SPACE_ON_RAM_DISK' => 'Not enough space on ran disk',
	'CANNOT_SAVE_MACHINE_STATE' => 'Can not save machine state',
	'CANNOT_WRITE_TO_BACKUP_LOCATION' => 'Can not write to backup location',
	'CANNOT_COPY_STATE_TO_BACKUP_LOCATION' => 'Can not copy state to backup location',
	'CANNOT_COPY_IMAGE_TO_BACKUP_LOCATION' => 'Can not copy image to backup location',
	'CANNOT_MERGE_DISK_IMAGES' => 'Can not merge disk images',
	'CANNOT_REMOVE_OLD_DISK_IMAGE' => 'Can not remove old disk image',
	'CANNOT_REMOVE_STATE_FILE' => 'Can not remove state file',
	'CANNOT_CREATE_EMPTY_DISK_IMAGE' => '>can not create empty disk image',
	'CANNOT_RENAME_DISK_IMAGE' => 'Can not rename disk image',
	'CANNOT_CONNECT_TO_BACKEND' => 'Can not connect to backend',
	'WRONG_STATE_INFORMATION' => 'Wrong state information',
	'CANNOT_SET_DISK_IMAGE_OWNERSHIP' => 'Can not set disk image ownership',
	'CANNOT_SET_DISK_IMAGE_PERMISSION' => 'Can not set disk image permission',
	'CANNOT_RESTORE_MACHINE' => 'Can not restore machine',
	'CANNOT_LOCK_MACHINE' => 'Can not lock machine',
	'CANNOT_FIND_MACHINE' => 'Can not find machine',
	'CANNOT_COPY_STATE_FILE_TO_RETAIN' => 'Can not copy state file to retain',
	'RETAIN_ROOT_DIRECTORY_DOES_NOT_EXIST' => 'Retain root directory does not exist',
	'BACKUP_ROOT_DIRECTORY_DOES_NOT_EXIST' => 'Backup root directory does not exist',
	'CANNOT_CREATE_DIRECTORY' => 'Can not create directory',
	'CANNOT_SAVE_XML' => 'Can not save XML',
	'CANNOT_SAVE_BACKEND_ENTRY' => 'Can not save backend entry',
	'CANNOT_SET_DIRECTORY_OWNERSHIP' => 'Can not set directory ownership',
	'CANNOT_SET_DIRECTORY_PERMISSION' => 'Can not set directory permission',
	
	'UNKNOWN_ERROR' => 'Unknown error',
);