<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Backup' => 'Backup',
  'Global' => 'Global',
  'Save' => 'Speichern',
  'Schedule' => 'Zeitplan',
  'Shutdown Schedule' => 'Shutdown Zeitplan',
  'allow Sound' => 'Ton zulassen',
  'allow USB' => 'USB zulassen',
  'at' => 'um',
  'every day' => 'jeden Tag',
  'max. Spice port' => 'max. Anzahl Spice Ports',
  'min. Spice port' => 'min. Anzahl Spice Ports',
  'no schedule' => 'kein Zeitplan',
  'no. of iterations' => 'Anzahl an Iterationen',
  'vm force start' => 'VM Start erzwingen',
  'vm force start hint' => <<<EOS
Force start virtual machine in the case of not being able<br/>to restore the virtual machine state during the backup process.<br/>
<b>Attention:</b> If set to Yes, this could lead to file system<br/>inconsistencies in the virtual machine.
EOS
,
);
