<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Create' => 'Erzeugen',
  'Create Group' => 'Benutzergruppe erzeugen',
  'Edit Group "{name}"' => 'Benutzergruppe "{name}" bearbeiten',
  'Import' => '',
  'Import Groups' => 'Benutzergruppen importieren',
  'Manage Groups' => 'Benutzergruppen verwalten',
  'Name' => '',
  'Save' => 'Speichern',
  'ext. Name' => '',
  'group already imported' => 'Benutzergruppe ist bereits importiert.',
  'group already imported; different groupnames found' => 'Benutzergruppe ist bereits importiert. Verschiedene Gruppennamen gefunden.',
  'please define a display name' => 'display name darf nicht leer sein!',
);
