<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Assigned VMs' => 'Zugewiesene VMs',
  'Create' => 'Erzeugen',
  'Download Spice Client' => '',
  'Dynamic Virtual Machines' => 'Dynamische VM\'s',
  'Dynamic Virtual Machines Tooltip' => 'Liste der definierten dynamischen VM\'s',
  'Links' => '',
  'Network' => 'Netzwerk',
  'Node' => 'Rechner',
  'Nodes' => 'Rechner',
  'Nodes Tooltip' => 'Liste aller Rechner',
  'Node Create Tooltip' => '',
  'Node View Tooltip' => '',
  'Spice Client Tooltip' => '',
  'Persistent Virtual Machines' => 'Persistente VM\'s',
  'Persistent Virtual Machines Tooltip' => 'Liste der definierten persistenten VM\'s',
  'Storage Pool' => '',
  'Storage Pools' => '',
  'Storage Pools Tooltip' => '',
  'Storage Pool Create Tooltip' => '',
  'Storage Pool View Tooltip' => '',
  'Subnet Create Tooltip' => 'Erzeuge ein Netzwerk Subnet',
  'Subnet Tooltip' => '',
  'Subnets' => '',
  'Update' => 'Bearbeiten',
  'Upload Iso File' => '',
  'User' => 'Benutzer',
  'User Create Tooltip' => '',
  'User Tooltip' => '',
  'User Update Tooltip' => '',
  'View' => 'Anzeige',
  'Virtual Machine' => 'VM',
  'Virtual Machine Profile Update Tooltip' => '',
  'Virtual Machine Profile UploadIso Tooltip' => '',
  'Virtual Machine Profiles' => 'VM Profile',
  'Virtual Machine Template Update Tooltip' => '',
  'Virtual Machine Templates' => 'VM Templates',
  'Virtual Machine Update Tooltip' => '',
  'Virtual Machine Profile Create Tooltip' => 'Erzeuge ein neues VM Profil',
  'Virtual Machine Profiles Tooltip' => 'Liste der definierten VM Profile',
  'Virtual Machine Template Create Tooltip' => 'Erzeuge ein neues VM Template',
  'Virtual Machine Templates Tooltip' => 'Liste der definierten VM Templates',
  'VmList' => 'VM Liste',
  'VmList Tooltip' => 'Liste der nutzbaren VM\'s',
  'VM Pool' => '',
  'VM Pools' => '',
  'VM Pools Tooltip' => '',
  'VM Pool Create Tooltip' => '',
  'VM Pool View Tooltip' => '',
  'Group' => 'Benutzergruppen',
  'Group Create Tooltip' => 'Erzeuge eine neue Benutzergruppe',
  'Group Import Tooltip' => 'Importiere Benutzergruppen',
  'Group Tooltip' => 'Liste der definierten Benutzergruppen',
  'Group Update Tooltip' => 'Aktualisiere eine Benutzergruppe',
  'Import' => '',
);
