<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '"{nodename}" is already integrated!' => '"{nodename}" ist bereits im System vorhanden!',
  'Manage Nodes' => 'Rechner verwalten',
  'Name already in use!' => 'Dieser Name wird bereits verwendet!',
  'Node' => 'Rechner',
  'Not a valid IP Address!' => 'Keine gültige IP Adresse',
  'Type' => 'Typ',
  'View Node {name}' => 'Rechner \'{name}\' anzeigen',
  'host' => 'Rechner',
  'wizard.ip' => 'IP Addresse',
  'wizard.outputvar \'{var}\' missing' => 'wizard.outputvar: Variable: \'{var}\' nicht gefunden',
  'wizard.password' => 'Passwort',
  'wizard.passwordcheck' => 'Passwort Prüfung',
  'wizard.type' => 'Node Typ',
  'wizard.user' => 'Benutzer',
);
