<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Broadcast Address' => '',
  'Create' => 'Erzeugen',
  'Create subnet' => 'Subnet erzeugen',
  'Default Gateway' => '',
  'Domain Name' => 'Domain Name (inklusive " ")',
  'Domain Server(s)' => '',
  'IP Start Address' => '',
  'Manage Subnets' => '',
  'NTP Server(s)' => '',
  'Net Mask' => '',
  'Not a valid IP Address!' => 'Keine gültige IP Adresse',
  'Not within subnet {subnet}' => 'Nicht innerhalb des Subnet {subnet}',
  'Overlaps with range {range}' => 'Überlappt mit Range {range}',
  'Overlaps with subnet {subnet}' => 'Überlappt mit Subnet {subnet}',
  'Save' => 'Speichern',
  'Type' => 'Typ',
  'title' => '',
);
