<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Create dynamic VM' => 'Erzeuge eine dynamische VM',
  'Create persistent VM' => 'Erzeuge eine persistente VM',
  'Edit VM "{name}" ({type})' => 'VM "{name}" bearbeiten ({type})',
  'Golden Image activated!' => 'Golden Image aktiviert!',
  'Golden Image already activated!' => 'Golden Image ist bereits aktiviert!',
  'Migration finished' => 'Migration beendet',
  'No range found for VMPool!' => 'Keinen Network Range für den VM Pool gefunden!',
  'Parameter dn not found!' => 'Parameter dn nicht gefunden!',
  'VM Details "{name}"' => '',
  'VM with dn=\'{dn}\' not found!' => 'VM mit dn=\'{dn}\' nicht gefunden!',
  'dynamic VM Pools' => 'Dynamische VM Pools',
  'persistent VM Pools' => 'Persistente VM Pools',
  'Assign users to VM' => 'Benutzer mit einer VM verknüpfen',
  'Assigned users' => 'verknüpfte Benutzer',
  'Assignment saved!' => 'Verknüpfung(en) gespeichert!',
  'Description' => 'Beschreibung',
  'IP Address already in use!' => 'IP Adresse wird bereits benutzt!',
  'IP Address not in range!' => 'IP Adresse nicht im Bereich!',
  'IP Address required!' => 'IP Adresse notwendig!',
  'Manage {type} VMs' => '{type} VMs verwalten',
  'Migrate' => 'Migrieren',
  'Migrate VM "{name}"' => 'VM "{name} migrieren',
  'Name already in use!' => 'Name wird bereits benutzt!',
  'Nodes' => 'Rechner',
  'Please select a range!' => 'Bitte wählen Sie einen Bereich aus!',
  'Save' => 'Speichern',
  'Users' => 'Benutzer',
  'ip' => 'IP Adresse',
  'name' => 'Name',
  'sstClockOffset' => 'Clock Offset',
  'sstMemory' => 'Speicher',
  'sstVCPU' => 'CPU',
  'sstVolumeCapacity' => 'Laufwerksgröße',
  'staticIP' => 'andere IP Adresse',
  'title' => 'Titel',
  'Assigned groups' => 'verknüpfte Benutzergruppen',
  'Backup with dn=\'{dn}\' not found!' => '',
  'Groups' => 'Benutzergruppen',
  'Restore Vm started!' => 'Wiederherstellen der Vm gestartet!<br />Bitte warten Sie um mögliche Fragen, die während des Wiederherstellens auftreten, zu beantworten.',
  'Waiting for data' => 'Warten auf Antwort ...',
  'Should restore of Vm start?' => 'Vm kann wiederhergestellt werden!<br />Möchten Sie jetzt beginnen?',
);
