<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'global backup' => 'Globales Backup',
  'pool backup' => 'VM Pool Backup',
  'global cron' => 'Globaler Zeitplan',
  'interfaces' => 'Schnittstellen',
  'poolSound' => 'benutze Sound',
  'allowSound (gloabal: NO)' => 'Sound (global: NEIN)',
  'allowSound (gloabal: YES)' => 'Sound (global: JA)',
  'poolUsb' => 'benutze USB',
  'allowUsb (gloabal: NO)' => 'USB (global: NEIN)',
  'allowUsb (gloabal: YES)' => 'USB (global: JA)',
  'Assign groups to VM' => 'Benutzergruppen mit einer VM verknüpfen',
  'Assign groups to VM Pool' => 'Benutzergruppen mit einem VM Pool verknüpfen',
  'Assigned groups' => 'verknüpfte Benutzergruppen',
  'Groups' => 'Benutzergruppen',
  'Assign users to VM Pool' => 'Benutzer mit einem VM Pool verknüpfen',
  'Assigned users' => 'verknüpfte Benutzer',
  'Assignment saved!' => 'Verknüpfung(en) gespeichert!',
  'Create' => 'Erzeugen',
  'Create VM Pool' => 'VM Pool erzeugen',
  'Edit Storage Pool "{name}"' => 'Storage Pool "{name}" bearbeiten',
  'Edit VM Pool "{name}"' => 'VM Pool "{name}" bearbeiten',
  'Manage VM Pools' => 'VM Pools verwalten',
  'Save' => 'Speichern',
  'Users' => 'Benutzer',
  'brokerMax' => 'Broker Max',
  'brokerMin' => 'Broker Min',
  'brokerPreStart' => 'Broker Prestart',
  'changes the selection of StoragePools and Ranges!' => 'verändert die Auswahl an Storage Pools und Ranges!',
  'displayName' => 'Name',
  'nodes' => 'Rechner',
  'range' => 'Range',
  'storagepool' => 'Storage Pool',
  'description' => 'Beschreibung',
  'YES' => 'JA',
  'NO' => 'NEIN',
);
