<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Action' => 'Aktion',
  'Alternative upload method' => 'Alternative Möglichkeit des Upload',
  'Alternative upload method link' => 'http://www.foss-cloud.org/en/wiki/Upload_ISO-Files',
  'Architecture' => 'Architektur',
  'BaseProfile' => 'Basis-Profil',
  'Check ISO Copy' => 'ISO Kopieren prüfen',
  'Copy of ISO file still running!' => 'Das Kopieren der Iso Datei läuft noch!',
  'Create' => 'Erzeugen',
  'Create VMProfile' => 'Erzeuge VM Profil',
  'Description' => 'Beschreibung',
  'Edit VMProfile "{name}"' => 'VM Profile "{name}" bearbeiten',
  'Extension uploadprogress not installed!' => 'Die Erweiterung uploadprogress ist nicht installiert!',
  'File Name' => 'Dateiname',
  'Finished!' => 'Beendet!',
  'Iso File' => 'Iso Datei',
  'Language' => 'Sprache',
  'Manage VMProfiles' => 'VM Profile verwalten',
  'Name' => 'Name',
  'Name already in use!' => 'Name wird bereits verwendet!',
  'No file for upload!' => 'Keine Datei ausgewählt!',
  'No.' => 'Nr.',
  'Please use only a-z, A-Z, 0-9, the space and the _ character.' => 'Bitte nur die Zeichen a-z, A-Z, 0-9, _ und das Leerzeichen benutzen.',
  'Save' => 'Speichern',
  'Still copying!' => 'Kopieren läuft noch',
  'Unload message' => 'Achtung: Wenn Sie diese Seite verlassen wird der Upload gestoppt!\\nWollen Sie den Upload beenden?',
  'Upload' => 'Hochladen',
  'Upload Iso File' => 'Iso Datei hochladen',
  'Upload error ({errno}).' => 'Upload Fehler ({errno})',
  'Upload finished' => 'Die Datei ist hochgeladen!',
  'Upload finished ({total})' => 'Hochladen beendet ({total})',
  'Upload finished title' => 'Fertig',
  'Uploading... ({uploaded} of {total})' => 'Uploading... ({uploaded} von {total})',
  'sstClockOffset' => 'Clock Offset',
  'sstMemory' => 'Speicher',
  'sstVCPU' => 'CPU',
  'sstVolumeCapacity' => 'Laufwerksgröße',
  'step1' => 'Schritt I',
  'step1text' => 'Bitte zuerst ein Profil auswählen, das als Basis dienen soll!',
  'step2' => 'Schritt II',
  'step2text' => 'Wenn notwenig bitte die vordefinierten Werte überschreiben!',
  'title' => 'Titel',
);
