<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Description' => 'Beschreibung',
  'No Range in Subnet ({subnet}) found! <a href="{anker}">Please create one.</a>' => 'Kein Netzwerk Range im Subnet ({subnet}) gefunden! <a href="{anker}">Bitte einen anlegen.</a>',
  'No Subnet found! <a href="{anker}">Please create one.</a>' => 'Kein Netzwerk Subet gefunden! <a href="{anker}">Bitte einen anlegen.</a>',
  'No free IP in Range {range} (Subnet {subnet}) found!' => 'Keine freie IP Adresse im Netzwerk Range {range} (Subnet {subnet}) gefunden!',
  'No free IP in Ranges of VmPool {pool} found!' => 'Für den VM Pool {pool} wurde keine freie IP Adresse gefunden!',
  'No range found for VMPool!' => 'Kein Netzwerk Range für den VM Pool gefunden!',
  'No storagepool found for selected vmpool!' => 'Für den selektierten VM Pool konnte kein Storage Pool gefunden werden"!',
  'Start VM' => 'starte VM',
  'Unable to create Volume file!' => 'Volume Datei konnte nicht erzeugt werden!',
  'Check Volume Copy' => 'Überprüfe Laufwerks kopieren',
  'Copy of VM Template volume to VM volume still running!' => 'Das Kopieren des VM Template Laufwerkes in ein VM Laufwerk läuft noch!',
  'Create' => 'Erzeugen',
  'Cancel' => 'Abbrechen',
  'Create VmTemplate' => 'VM template erzeugen',
  'Edit VMTemplate "{name}"' => 'VMTemplate "{name}" bearbeiten',
  'Finished!' => 'Beendet!',
  'Manage VMTemplates' => 'VM Templates verwalten',
  'Name already in use!' => 'Name wird bereits verwendet!',
  'Node' => 'Rechner',
  'Ok' => 'Ok',
  'Profile' => 'Profil',
  'Save' => 'Speichern',
  'Still copying!' => 'Kopiert noch!',
  'ip' => 'IP Adresse',
  'sstClockOffset' => 'Clock Offset',
  'sstMemory' => 'Memory',
  'sstVCPU' => 'CPU',
  'sstVolumeCapacity' => 'Laufwerksgröße',
  'staticIP' => 'IP Adresse ändern',
  'step1' => 'Schritt I',
  'step1text' => 'Bitte zuerst ein Profil auswählen, das als Basis dienen soll!',
  'step2' => 'Schritt II',
  'step2text' => 'Bitte wählen Sie einen Knoten aus und wenn notwenig überschreiben Sie die vordefinierten Werte!',
  'title' => 'Titel',
);
