<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'findAll: neither attr nor filter set in criteria!' => '',
  'ldap_add failed ({errno}): {message}' => '',
  'ldap_bind failed ({errno}): {message}' => '',
  'ldap_connect to {server} failed' => '',
  'ldap_delete failed ({errno}): {message}' => '',
  'ldap_get_entries failed ({errno}): {message}' => '',
  'ldap_list failed ({errno}): {message}' => '',
  'ldap_mod_del failed ({errno}): {message}' => '',
  'ldap_modify failed ({errno}): {message}' => '',
  'ldap_read failed ({errno}): {message}' => '',
  'ldap_rename failed ({errno}): {message}' => '',
  'ldap_search failed ({errno}): {message}' => '',
);
