<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Action "{actionName}" (line {lineno} following) has the following errors: {messages}' => '',
  'CANCEL' => '',
  'Destination directory "{dirName}" not allowed to overwrite!' => '',
  'Destination file "{destName}" not allowed to overwrite!' => '',
  'Directory "{dirName}" not found!' => '',
  'Do you really want to start this patch?' => '',
  'Error in line {lineno}: Action "{actionName}"; {message}' => '',
  'Error in line {lineno}: Action without "name" attribute found!' => '',
  'Error in line {lineno}: Parameter without "name" attribute within the action "{actionName}" found!' => '',
  'Error in line {lineno}: Parameter with empty "name" attribute within the action "{actionName}" found!' => '',
  'Error: Parameter with name "{paramName}" within the action "{actionName}" not found!' => '',
  'Error in line {lineno}: Unknown action "{actionName}" found!' => '',
  'Error in line {lineno}: Parameter without "name" attribute within the mainClass found!' => '',
  'Error in line {lineno}: Parameter with empty "name" attribute within the mainClass found!' => '',
  'Error: Parameter with name "{paramName}" within the mainClass not found!' => '',
  'Error in line {lineno}: Unknown finish type "{finishType}" found!' => '',
  'finished: {message}!' => '',
  'finished: {actionCount} of {actionCount} actions processed!' => '',
  'File "{fileName}" not found!' => '',
  'List of available patches' => '',
  'Mandatory parameter "{paramName}" missing!' => '',
  'Mandatory XML tag "{xmlTag}" missing!' => '',
  'OK' => '',
  'Part progress' => '',
  'Patch: {title}' => '',
  'Patch (version from {minVersion} to {maxVersion}) not allowed with this actual version ({actVersion})' => '',
  'The two parameters "{paramName1}" and "{paramName2}" must both have a &lt;set&gt; or not!' => '',
  'The two parameters "{paramName1}" and "{paramName2}" must both have the same number of &lt;item&gt; in their own &lt;set&gt;!' => '',
  'Total progress' => '',
  'Unable to delete file "{fileName}"!' => '',
  'Unable to move patch to archive!' => '',
  'Unable to delete patch!' => '',
  'Unknown action "{actionName}"!' => '',
  'Unknown patch with name "{patchName}"!' => '',
  'start patch' => '',
);
