<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Class "{class}" not found for removeAttributesByObjectClass' => '',
  'Failed to createEntry for ldap_add. No objectClass(es) defined!' => '',
  'Ldap record "{class}" has an invalid configuration for relation "{relation}". It must specify the relation type, the related active record class and the foreign key.' => '',
  'Method "{class}.{method}" is not defined.' => '',
  'Parse value from attr \'{name}\' failed! (Wrong reg pattern)' => '',
  'Property "{class}.{property}" is not defined.' => '',
  'The entry cannot be inserted to LDAP because it is not new.' => '',
  'The entry cannot be moved within LDAP because it is new.' => '',
  'The entry cannot be updated within LDAP because it is new.' => '',
  'Unknown objectClass "{class}"!' => '',
  'Wrong result count ({count}) on findByDn' => '',
  'findSubTree failed: parent \'{dn}\' not read!' => '',
  'findSubTree failed: used class is not type or subtype of \'LdapSubTree\'!' => '',
  '{class} does not have relation "{name}".' => '',
);
