<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Can\'t move uploaded file.' => 'Impossible de déplacer le fichier téléchargé',
  'Can\'t open input stream.' => 'Impossible d’ouvrir le flux d’entrée.',
  'Can\'t open output stream.' => 'Impossible d’ouvrir le flux de sortie.',
  'Can\'t open temporary directory.' => 'Impossible d’ouvrir le répertoire temporaire',
  'ISO files' => 'Fichiers ISO',
  'locale' => 'fr_FR',
);
