<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'assignedVMs' => 'MVs assignées',
  'createSubnet' => 'Créer sous-réseau',
  'createUser' => 'Créer utilisateur',
  'createVmProfile' => 'Créer profil',
  'createVmTemplate' => 'Créer modèle',
  'editVmProfile' => 'Modifier profil MV',
  'editVmTemplate' => 'Modifier modèle MV',
  'manageNodes' => 'Gérer noeuds',
  'manageSubnets' => 'Gérer sous-réseaux',
  'manageUser' => 'Gérer utilisateur',
  'manageVMProfiles' => 'Gérer profils MV',
  'manageVMTemplates' => 'Gérer modèles',
  'manageVMs' => 'Gérer MVs',
  'updateUser' => 'Actualiser utilisateur',
  'updateVM' => 'Actualiser MV',
  'uploadIso' => 'Télécharger fichier Iso',
  'viewNode' => 'Voir noeud',
  'viewVM' => 'Voir MV',
);
