<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Assigned VMs' => 'MV assignées',
  'Create' => 'Créer',
  'Download Spice Client' => 'Télécharger Client Spice',
  'Dynamic Virtual Machines' => 'MVs dynamiques',
  'Dynamic Virtual Machines Tooltip' => 'Liste de machines virtuelles dynamiques',
  'Links' => 'Liens',
  'Network' => 'Réseau',
  'Node' => 'Noeud',
  'Nodes' => ' Noeuds',
  'Nodes Tooltip' => 'Liste de noeuds définis',
  'Node Create Tooltip' => 'Création de noeuds',
  'Node View Tooltip' => 'Affichage de noeuds',
  'Spice Client Tooltip' => 'Description de Client Spice',	
  'Persistent Virtual Machines' => 'MVs persistantes',
  'Persistent Virtual Machines Tooltip' => 'Liste de machines virtuelles persistantes',
  'Storage Pool' => 'Pool de Stockage',
  'Storage Pools' => 'Pools de Stockage',
  'Storage Pools Tooltip' => 'Pools de Stockage',
  'Storage Pool Create Tooltip' => 'Création de pools de stockage',
  'Storage Pool View Tooltip' => 'Affichage de pools de stockage',
  'Subnet Create Tooltip' => 'Créer sous-réseau',
  'Subnet Tooltip' => 'Sous-réseau',
  'Subnets' => 'Sous-réseaux',
  'Update' => 'Modifier',
  'Upload Iso File' => 'Télécharger fichier ISO',
  'User' => 'Utilisateur',
  'User Create Tooltip' => 'Créer nouveau utilisateur',
  'User Tooltip' => 'Utilisateur',
  'User Update Tooltip' => 'Modifier utilisateur',
  'View' => 'Affichage',
  'Virtual Machine' => 'Machine Virtuelle',
  'Virtual Machine Profile Update Tooltip' => 'Actualisation de profil de Machine Virtuelle',
  'Virtual Machine Profile UploadIso Tooltip' => 'Téléchargement Iso de profil de Machine Virtuelle',
  'Virtual Machine Profiles' => 'Profils',
  'Virtual Machine Template Update Tooltip' => 'Actualisation de modèle de Machine Virtuelle',
  'Virtual Machine Templates' => 'Modèles MV',
  'Virtual Machine Update Tooltip' => 'Actualisation de Machine Virtuelle',
  'Virtual Machine Profile Create Tooltip' => 'Créer un nouveau profil MV',
  'Virtual Machine Profiles Tooltip' => 'Liste de profils MV définis',
  'Virtual Machine Template Create Tooltip' => 'Créer nouveau modèle MV',
  'Virtual Machine Templates Tooltip' => 'Liste de modèles MV définis',
  'VmList' => 'Liste MV',
  'VmList Tooltip' => 'Liste de MVs disponibles',
  'VM Pool' => 'Pool MV',
  'VM Pools' => 'Pools MV',
  'VM Pools Tooltip' => 'Pools MV',
  'VM Pool Create Tooltip' => 'Création de pool MV',
  'VM Pool View Tooltip' => 'Affichage de pool MV',
);
