<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Name already in use!' => 'Ce nom est déjà en cours d<92>utilisation',
  'Not a valid IP Address!' => 'Adresse IP incorrecte',
  'wizard.outputvar \'{var}\' missing' => 'wizard.outputvar \'{var}\'manquant',
 '"{nodename}" is already integrated!' => '"{nodename}" est déjà intégré',
  'Manage Nodes' => 'Gérer noeuds',
  'View Node' => 'Afficher noeud',
  'Node' => 'Noeud',
  'Type' => 'Type',
  'wizard.type' => 'Type de noeud',
  'wizard.ip' => 'IP',
  'wizard.user' => 'Utilisateur',
  'wizard.password' => 'Mot de passe',
  'wizard.passwordcheck' => 'Introduire le mot de passe à nouveau',

  'wizard.test1.title' => 'Réseau de vérification d’intégration de noeuds',
  'wizard.test1.0' => 'Le script a été exécuté avec succès.',
  'wizard.test1.1' => 'Le script s’est terminé dans un état indéfini.',
  'wizard.test1.2' => 'Nom de module pas approuvé.',

  'wizard.prov1.title' => 'Système de fichiers de mise en service d’intégration de noeuds',
  'wizard.prov1.0' => 'Le script a été exécuté avec succès.',
  'wizard.prov1.1' => 'Le script s’est terminé dans un état indéfini.',
);
