<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Incorrect username or password.' => 'Nom d’utilisateur ou mot de passe incorrect.',
  'Incorrect username.' => 'Nom d’utilisateur incorrect.',
  'Incorrect password.' => 'Mot de passe incorrect.',
  'Password' => 'Mot de passe',
  'Realm' => 'Division',
  'Remember me next time' => 'Se souvenir de moi la prochaine fois',
  'User not assigned to realm.' => 'Utilisateur non assigné à division',
  'Username' => 'Nom d’utilisateur',
);
