<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Broadcast Address' => 'Adresse de diffusion',
  'Create' => 'Créer',
  'Create subnet' => ' Créer sous-réseau',
  'Default Gateway' => 'Passerelle par défaut',
  'Domain Name' => 'Nom de domaine (avec " ")',
  'Domain Server(s)' => 'Serveur de domaine(s)',
  'IP Start Address' => 'Adresse de démarrage IIP',
  'Manage Subnets' => 'Gérer sous-réseaux',
  'NTP Server(s)' => 'Serveur(s) NTP',
  'Not a valid IP Address!' => 'Adresse IP incorrecte',
  'Save' => 'Sauvegarder',
  'Net Mask' => 'Masque de sous-réseau',
  'Type' => 'Type',
  'Overlaps with subnet {subnet}' => 'Chevauche le sous-réseau {subnet}',
  'Overlaps with range {range}' => ' Chevauche la gamme {range}',
  'Not within subnet {subnet}' => 'Hors de sous-réseau {subnet}',
  'title' => 'titre',
);
