<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Admin' => 'Admin',
  'Assign VMs to user' => 'Assigner MVs à utilisateur',
  'Assigned VMs' => 'MVs assignées',
  'Assignment saved!' => 'Assignation sauvegardée',
  'Create' => 'Créer',
  'Create User' => 'Créer utilisateur',
  'Edit User "{name}"' => 'Modifier utilisateur "{name}"',
  'Female' => 'Femelle',
  'Mail already in use!' => 'Ce courier est déjà en cours d’utilisation',
  'Male' => 'Mâle',
  'Manage User' => 'Gérer utilisateur',
  //'PHP function mhash and mhash_keygen_s2k for encryption type "SSHA"' => 'PHP function mhash et mhash_keygen_s2k pour le type de cryptage "SSHA"',
  //'PHP function mhash needed to encode password for encryption type "SSHA"' => 'PHP function mhash requise pour encoder le mot de passe pour le type de cryptage "SSHA"',
  'Save' => 'Sauvegarder',
  //'Unknown encryption type "{type}" for LDAP user authentication!' => 'Type de cryptage "{type}" pour authentification d’utilisateur LDAP inconnu',
  //'Username already in use!' => 'Ce nom d’utilisateur est déjà en cours dutilisation',
  'VM User' => 'Utilisateur MV',
  'VMs' => 'MVs',
  //'{attribute} is invalid. Please use only<br/>"0-9+()" characters and blank.' => '{attribute} n’est pas valide. Veuillez utiliser uniquement les caractères <br/>"0-9+()" et des espaces.',
  'gender' => 'Genre',
  'givenname' => 'Nom de famille',
  'mail' => 'Email',
  'mobile' => 'Mobile',
  'password' => 'Mot de passe',
  'passwordcheck' => 'Insérer mot de passe à nouveau',
  'surname' => 'Prénom',
  'telephone' => 'Téléphone',
  'username' => 'Nom d’utilisateur',
  'userrole' => 'Rôle d’utilisateur',
);
