<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Create dynamic VM' => 'Créer MV dynamique',
  'Create persistent VM' => ' Créer MV persistante',
  'Edit VM "{name}" ({type})' => 'Modifier MV "{name}" ({type})',
  'Golden Image activated!' => 'Golden Image active',
  'Golden Image already activated!' => 'Golden Image est déjà active',
  'Migration finished' => 'Migration terminée',
  'No range found for VMPool!' => 'Pas de gamme trouvée pour PoolMV',
  'Parameter dn not found!' => 'Paramètre dn pas trouvé',
  'VM Details "{name}"' => 'Détails MV "{name}"',
  'VM with dn=\'{dn}\' not found!' => 'VM avec dn=\'{dn}\' pas trouvée',
  'dynamic VM Pools' => 'Pools MV dynamiques',
  'persistent VM Pools' => ' Pools MV persistantes',
  'Assign users to VM' => 'Assigner utilisateurs à MV',
  'Assigned users' => 'Utilisateurs assignés',
  'Assignment saved!' => 'Assignation sauvegardée',
  'Description' => 'Description',
  'IP Address already in use!' => 'Cette adresse IP est déjà en cours d’utilisation',
  'IP Address not in range!' => 'Adresse IP hors de gamme',
  'IP Address required!' => 'Adresse IP requise',
  'Manage {type} VMs' => 'Gérer MVs {type}',
  'Migrate' => 'Migrer',
  'Migrate VM "{name}"' => 'Migrer MVs',
  'Name already in use!' => 'Ce nom est déjà en cours d’utilisation',
  'Nodes' => 'Noeuds',
  'Please select a range!' => 'Veuillez sélectionner une gamme',
  'Save' => 'Sauvegarder',
  'Users' => 'Utilisateurs',
  'ip' => 'Adresse IP',
  'name' => 'Nom',
  'sstClockOffset' => 'Décalage d’horloge',
  'sstMemory' => 'Mémoire',
  'sstVCPU' => 'CPU',
  'sstVolumeCapacity' => 'Capacité du volume',
  'staticIP' => 'Changer adresse IP',
  'title' => 'Titre',
);
