<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Assign users to VM Pool' => 'Assigner utilisateurs à Pool MV',
  'Assigned users' => 'Utilisateurs assignés',
  'Assignment saved!' => 'Assignation sauvegardée',
  'Create' => 'Créer',
  'Create VM Pool' => 'Créer Pool MV',
  'Edit Storage Pool "{name}"' => 'Modifier Pool de stockage "{name}"',
  'Edit VM Pool "{name}"' => 'Modifier Pool MV "{name}"',
  'Manage VM Pools' => 'Gérer Pools MV',
  'Save' => 'Sauvegarder',
  'Users' => 'Utilisateurs',
  'brokerMax' => 'Broker Max',
  'brokerMin' => 'Broker Min',
  'brokerPreStart' => 'Broker avant démarrage',
  'changes the selection of StoragePools and Ranges!' => 'modifie la sélection de Pools de stockage et gammes',
  'displayName' => 'Nom',
  'nodes' => 'Noeuds',
  'range' => 'Gamme',
  'storagepool' => 'Pool de stockage',
  'description' => 'Description',
);
