<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'Description' => 'Description ',
  'No Range in Subnet ({subnet}) found! <a href="{anker}">Please create one.</a>' => 'Pas de gamme trouvée au sous-réseau ({subnet}) <a href="{anker}">Veuillez en créer une.',
  'No Subnet found! <a href="{anker}">Please create one.</a>' => 'Pas de sous-réseau trouv <a href="{anker}">Veuillez en créer un. </a>',
  'No free IP in Range {range} (Subnet {subnet}) found!' => 'Pas de IP libre trouve dans la gamme {range} (sous-réseau {subnet})',
  'No free IP in Ranges of VmPool {pool} found!' => 'Pas de IP libre trouvée dans les gammes de Pool MV {pool}',
  'No range found for VMPool!' => 'Pas de gamme trouvée pour Pool MV',
  'No storagepool found for selected vmpool!' => 'Pas de pool de stockage trouvée pour MV pool selectionnée',
  'Start VM' => 'Démarrer MV',
  'Unable to create Volume file!' => 'Impossible de créer le fichier de volume',
  'Check Volume Copy' => 'Vérifier copie de volume',
  'Copy of VM Template volume to VM volume still running!' => 'Copie de modèle MV  volume MV en cours',
  'Create' => 'Créer',
  'Create VmTemplate' => 'Créer modèle MV',
  'Edit VMTemplate "{name}"' => 'Modifier modèle MV "{name}"',
  'Finished!' => 'Terminé',
  'Manage VMTemplates' => 'Gérer modèles MV',
  'Name already in use!' => 'Ce nom est dj en cours d’utilisation',
  'Node' => 'Noeud',
  'Profile' => 'Profil',
  'Save' => 'Sauvegarder',
  'Still copying!' => 'Copie en cours',
  'ip' => 'Adresse IP',
  'sstClockOffset' => 'Décalage d’horloge',
  'sstMemory' => 'Mémoire',
  'sstVCPU' => 'CPU',
  'sstVolumeCapacity' => 'Capacité du volume',
  'staticIP' => 'changer adresse IP',
  'step1' => 'Étape I',
  'step1text' => 'Veuillez sélectionner un profil',
  'step2' => 'Étape II',
  'step2text' => 'Veuillez sélectionner un noeud et modifier les valeurs par dfaut si nécessaire',
  'title' => 'Titre',
);
